gerritServers:
  kubernetes:
  - namespace: default
    label:
      name: app
      value: gerrit-slave
    containerName: gerrit-slave
    port: 8080
    username: admin
    password: secret
  federatedPrometheus:
  - host: prometheus.example.com
    port: 9090
    username: admin
    password: secret
  other:
  - host: gerrit.example.com
    username: admin
    password: secret
    healthcheck: false
    promtail:
      storagePath: /var/promtail
      logPath: /var/gerrit/logs
namespace: namespace
tls:
  skipVerify: true
  caCert:
istio:
  enabled: false
  cert:
  key:
  jwt:
    cert:
    key:
    issuer:
monitoring:
  prometheus:
    server:
      host: prometheus.example.com
      username:
      password:
      tls:
        cert:
        key:
    alertmanager:
      slack:
        apiUrl: https://hooks.slack.com/services/xxx/xxx
        channel: '#alerts'
  grafana:
    host: grafana.example.com
    tls:
      cert:
      key:
    admin:
      username: admin
      password: secret
    ldap:
      enabled: false
      host:
      port: ""
      password:
      bind_dn:
      accountBases: "[]"
      groupBases: "[]"
    dashboards:
      editable: false
logging:
  loki:
    host: loki.example.com
    username:
    password:
    s3:
      protocol: https
      host: s3.eu-de-1.example.com
      accessToken: abcd
      secret: "1234"
      bucket: bucket
      region: eu-de-1
    tls:
      cert:
      key:
