#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ if not data.values.istio.enabled:
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-server-tls
  namespace: #@ data.values.namespace
type: kubernetes.io/tls
data:
  tls.crt: #@ base64.encode(data.values.monitoring.prometheus.server.tls.cert)
  tls.key: #@ base64.encode(data.values.monitoring.prometheus.server.tls.key)
#@ end
