{
 "title": "Gerrit - NOTEDB Latency",
 "tags": [ "gerrit" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "Gerrit Instance",
    "query": {
     "query": "label_values(git_upload_pack_phase_writing_total,pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "UPDATE notedb latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "notedb_update_latency{pod=\"$pod\", quantile=\"0.999\"}",
     "legendFormat": "quantile: {{quantile}}"
    }
   ]
  },
  {
   "title": "STAGE_UPDATE notedb latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "notedb_stage_update_latency{pod=\"$pod\", quantile=\"0.999\"}",
     "legendFormat": "quantile: {{quantile}}"
    }
   ]
  },
  {
   "title": "READ notedb latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "s", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "notedb_read_latency{pod=\"$pod\", quantile=\"0.999\"}",
     "legendFormat": "quantile: {{quantile}}"
    }
   ]
  },
  {
   "title": "PARSE notedb latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "s", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "notedb_parse_latency{pod=\"$pod\", quantile=\"0.999\"}",
     "legendFormat": "quantile: {{quantile}}"
    }
   ]
  },
  {
   "title": "READ ALL EXTERNAL IDS notedb latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "s", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "notedb_read_all_external_ids_latency{pod=\"$pod\"}",
     "legendFormat": "quantile: {{quantile}}"
    }
   ]
  }
 ]
}