{
 "title": "Gerrit - Process",
 "tags": [
  "gerrit",
  "gerrit-monitoring"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "Gerrit Instance",
    "query": {
     "query": "label_values(git_upload_pack_phase_writing_total,pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "System load",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "System load" }
   ],
   "targets": [
    {
     "expr": "proc_cpu_system_load{pod=\"$pod\"}",
     "legendFormat": "system load"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes", "label": "Memory Consumption" }
   ],
   "targets": [
    {
     "expr": "proc_jvm_memory_heap_committed{pod=\"$pod\"}",
     "legendFormat": "committed heap"
    },
    {
     "expr": "proc_jvm_memory_heap_used{pod=\"$pod\"}",
     "legendFormat": "used heap"
    },
    {
     "expr": "jgit_block_cache_cache_used{pod=\"$pod\"}",
     "legendFormat": "JGit block cache"
    },
    {
     "expr": "proc_jvm_memory_non_heap_used{pod=\"$pod\"}",
     "legendFormat": "used non-heap"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "CPU cores" }
   ],
   "targets": [
    {
     "expr": "rate(proc_cpu_usage{pod=\"$pod\"}[5m])",
     "legendFormat": "used CPUs"
    },
    {
     "expr": "proc_cpu_num_cores{pod=\"$pod\"}",
     "legendFormat": "available CPUs"
    }
   ]
  },
  {
   "title": "Java - % of time spent in GC",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "percentunit", "label": "% of time spent in GC" }
   ],
   "targets": [
    {
     "expr": "increase(proc_jvm_gc_time_G1_Young_Generation{pod=\"$pod\"}[2m])/increase(proc_uptime{pod=\"$pod\"}[2m])",
     "legendFormat": "gc time G1 young gen"
    },
    {
     "expr": "increase(proc_jvm_gc_time_G1_Old_Generation{pod=\"$pod\"}[2m])/increase(proc_uptime{pod=\"$pod\"}[2m])",
     "legendFormat": "gc time G1 old gen"
    },
    {
     "expr": "increase(proc_jvm_gc_time_PS_Scavenge{pod=\"$pod\"}[2m])/increase(proc_uptime{pod=\"$pod\"}[2m])",
     "legendFormat": "gc time PS Scavange"
    },
    {
     "expr": "increase(proc_jvm_gc_time_PS_MarkSweep{pod=\"$pod\"}[2m])/increase(proc_uptime{pod=\"$pod\"}[2m])",
     "legendFormat": "gc time PS MarkSweep"
    },
    {
     "expr": "increase(proc_jvm_gc_time_ZGC{pod=\"$pod\"}[2m])/increase(proc_uptime{pod=\"$pod\"}[2m])",
     "legendFormat": "gc time ZGC"
    },
    {
     "expr": "increase(proc_jvm_gc_time_ShenandoahGC{pod=\"$pod\"}[2m])/increase(proc_uptime{pod=\"$pod\"}[2m])",
     "legendFormat": "gc time ShenandoahGC"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "Live Threads" }
   ],
   "targets": [
    {
     "expr": "proc_jvm_thread_num_live{pod=\"$pod\"}",
     "legendFormat": "Java live threads"
    }
   ]
  },
  {
   "title": "Java open file descriptors",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "Open File Descriptors" }
   ],
   "targets": [
    {
     "expr": "jgit_block_cache_open_files{pod=\"$pod\"}",
     "legendFormat": "jgit block cache"
    },
    {
     "expr": "proc_num_open_fds{pod=\"$pod\"}-jgit_block_cache_open_files{pod=\"$pod\"}",
     "legendFormat": "other"
    }
   ]
  },
  {
   "title": "JGit block cache",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percentunit", "label": "miss ratio" }
   ],
   "targets": [
    {
     "expr": "increase(jgit_block_cache_miss_count{pod=\"$pod\"}[2m])/(increase(jgit_block_cache_hit_count{pod=\"$pod\"}[2m])+increase(jgit_block_cache_miss_count{pod=\"$pod\"}[2m]))",
     "legendFormat": "miss ratio"
    },
    {
     "expr": "increase(jgit_block_cache_eviction_count{pod=\"$pod\"}[2m])/(increase(jgit_block_cache_hit_count{pod=\"$pod\"}[2m])+increase(jgit_block_cache_miss_count{pod=\"$pod\"}[2m]))",
     "legendFormat": "eviction ratio"
    }
   ]
  }
 ]
}