{
 "title": "Gerrit - QUERY Latency",
 "tags": [ "gerrit" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Gerrit Instance",
    "query": "label_values(git_upload_pack_phase_writing_total, instance)"
   },
   {
    "name": "replica",
    "label": "Replica",
    "query": "label_values(git_upload_pack_phase_writing_total{instance=\"$instance\"}, replica)"
   }
  ]
 },
 "panels": [
  {
   "title": "TOTAL query latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "query_query_latency_total{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "quantile: {{quantile}}"
    }
   ]
  },
  {
   "title": "ACCOUNTS query latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "s", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "query_query_latency_accounts{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "quantile: {{quantile}}"
    }
   ]
  },
  {
   "title": "CHANGES query latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "s", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "query_query_latency_changes{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "quantile: {{quantile}}"
    }
   ]
  },
  {
   "title": "GROUPS query latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "s", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "query_query_latency_groups{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "quantile: {{quantile}}"
    }
   ]
  },
  {
   "title": "PROJECTS query latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "s", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "query_query_latency_projects{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "quantile: {{quantile}}"
    }
   ]
  }
 ]
}