{
 "title": "Kubernetes / Applications / Gerrit",
 "description": "Gerrit dashboard with metrics from JMX.",
 "tags": [
  "application",
  "gerrit"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_statefulset_created{statefulset=~\".*gerrit.*\"}, namespace)"
    }
   },
   { "name": "container", "label": "Container", "query": "gerrit" },
   {
    "name": "statefulset",
    "query": {
     "query": "label_values(kube_statefulset_created{namespace=\"$namespace\", statefulset=~\"^.+-gerrit\"}, statefulset)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(scrape_duration_seconds{namespace=\"$namespace\", container=\"$container\", service=\"$statefulset-jmx\"}, service)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(scrape_duration_seconds{namespace=\"$namespace\", container=\"$container\", service=\"$service\"}, pod)"
    }
   },
   {
    "name": "mempool",
    "query": {
     "query": "label_values(jvm_memory_pool_bytes_used{namespace=\"$namespace\", pod=\"$pod\", service=\"$service\"},pool)"
    }
   },
   {
    "name": "memarea",
    "query": {
     "query": "label_values(jvm_memory_bytes_used{namespace=\"$namespace\",pod=\"$pod\",service=\"$service\"}, area)"
    }
   },
   {
    "name": "core_queue",
    "query": {
     "query": "{__name__ =~ \"queue_.*_active_threads\",pod=\"$pod\"}"
    }
   },
   { "name": "upload_pack_operation", "query": "CLONE,FETCH" }
  ]
 },
 "panels": [
  {
   "title": "Main",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Version",
     "type": "stat",
     "gridPos": { "h": 3, "w": 10, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(gerrit_build_info{pod=\"$pod\"}) by (pod, version, revision, javaversion)",
       "legendFormat": "{{javaversion}}"
      }
     ]
    },
    {
     "title": "Status",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 10, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{pod=\"$pod\"}"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - max(container_start_time_seconds{pod=\"$pod\"})"
      }
     ]
    },
    {
     "title": "Start time",
     "type": "stat",
     "gridPos": { "h": 3, "w": 10, "x": 14, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(container_start_time_seconds{pod=\"$pod\"}) * 1000"
      }
     ]
    },
    {
     "title": "CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (pod) (irate(proc_cpu_usage{pod=\"$pod\"}[1m]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", pod=\"$pod\", resource=\"cpu\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$namespace\", pod=\"$pod\", resource=\"cpu\"})",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "Memory Usage (WSS)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\", pod=\"$pod\", container!=\"\", image!=\"\"}) by (container)",
       "legendFormat": "{{container}}"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", pod=\"$pod\", resource=\"memory\"}\n)\n",
       "legendFormat": "requests"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$namespace\", pod=\"$pod\", resource=\"memory\"}\n)\n",
       "legendFormat": "limits"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Storage bytes used",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "kubelet_volume_stats_used_bytes{job=\"kubelet\",persistentvolumeclaim=\"gerrit-site-$pod\"} / kubelet_volume_stats_capacity_bytes{job=\"kubelet\",namespace=\"$namespace\",persistentvolumeclaim=\"gerrit-site-$pod\"}",
       "legendFormat": "Percent"
      },
      {
       "expr": "kubelet_volume_stats_used_bytes{job=\"kubelet\",persistentvolumeclaim=\"gerrit-site-$pod\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "kubelet_volume_stats_capacity_bytes{job=\"kubelet\",persistentvolumeclaim=\"gerrit-site-$pod\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Storage inodes used",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "kubelet_volume_stats_inodes_used{job=\"kubelet\",namespace=\"$namespace\",persistentvolumeclaim=\"gerrit-site-$pod\"} / kubelet_volume_stats_inodes{job=\"kubelet\",namespace=\"$namespace\",persistentvolumeclaim=\"gerrit-site-$pod\"}",
       "legendFormat": "Percent"
      },
      {
       "expr": "kubelet_volume_stats_inodes_used{job=\"kubelet\",namespace=\"$namespace\",persistentvolumeclaim=\"gerrit-site-$pod\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "kubelet_volume_stats_inodes{job=\"kubelet\",namespace=\"$namespace\",persistentvolumeclaim=\"gerrit-site-$pod\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Throughput",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by(pod) (rate(container_fs_reads_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", container!=\"\", namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "Reads"
      },
      {
       "expr": "sum by(pod) (rate(container_fs_writes_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", container!=\"\", namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "Writes"
      }
     ]
    },
    {
     "title": "IOPS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ceil(sum by(pod) (rate(container_fs_reads_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", container!=\"\", namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval])))",
       "legendFormat": "Reads"
      },
      {
       "expr": "ceil(sum by(pod) (rate(container_fs_writes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", container!=\"\",namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval])))",
       "legendFormat": "Writes"
      }
     ]
    },
    {
     "title": "Open file descriptors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "sum by (pod) (proc_num_open_fds{pod=\"$pod\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "sum by (pod) (jgit_block_cache_open_files{pod=\"$pod\"})",
       "legendFormat": "jgit"
      }
     ]
    }
   ]
  },
  {
   "title": "Services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "sshd (maybe delta)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "sum by (pod, __name__) (sshd_sessions_connected{namespace=\"$namespace\",pod=\"$pod\"})",
       "legendFormat": "sessions_connected"
      },
      {
       "expr": "sum by (pod, __name__) (rate(sshd_sessions_authentication_failures_total{pod=\"$pod\"}[2m:1m]))",
       "legendFormat": "authentication_failures"
      }
     ]
    },
    {
     "title": "jetty",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
     "targets": [
      {
       "expr": "sum by (pod, __name__) (http_server_jetty_threadpool_active_threads{pod=\"$pod\"})",
       "legendFormat": "active_threads"
      },
      {
       "expr": "sum by (pod, __name__) (http_server_jetty_threadpool_idle_threads{pod=\"$pod\"})",
       "legendFormat": "idle_threads"
      },
      {
       "expr": "sum by (pod, __name__) (http_server_jetty_threadpool_reserved_threads{pod=\"$pod\"})",
       "legendFormat": "reserved_threads"
      },
      {
       "expr": "sum by (pod, __name__) (http_server_jetty_threadpool_max_pool_size{pod=\"$pod\"})",
       "legendFormat": "max_pool_size"
      },
      {
       "expr": "sum by (pod, __name__) (http_server_jetty_threadpool_min_pool_size{pod=\"$pod\"})",
       "legendFormat": "min_pool_size"
      },
      {
       "expr": "sum by (pod, __name__) (http_server_jetty_threadpool_pool_size{pod=\"$pod\"})",
       "legendFormat": "pool_size"
      },
      {
       "expr": "sum by (pod, __name__) (http_server_jetty_threadpool_queue_size{pod=\"$pod\"})",
       "legendFormat": "queue_size"
      }
     ]
    },
    {
     "title": "jgit",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (pod, __name__) (jgit_block_cache_cache_used{pod=\"$pod\"})",
       "legendFormat": "cache_used"
      },
      {
       "expr": "sum by (pod, __name__) (irate(jgit_block_cache_miss_count{pod=\"$pod\"}[1m]))",
       "legendFormat": "cache_misses"
      },
      {
       "expr": "sum by (pod, __name__) (irate(jgit_block_cache_hit_count{pod=\"$pod\"}[1m]))",
       "legendFormat": "cache_hits"
      }
     ]
    }
   ]
  },
  {
   "title": "Core queues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Core queue tasks scheduled",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "sum by (pod, __name__) ({__name__=~\"queue_.*_scheduled_tasks\",pod=\"$pod\"})",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Core queue [$core_queue]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
     "repeat": "core_queue",
     "targets": [
      {
       "expr": "group by(pod, __name__) ({__name__=\"queue_${core_queue}_active_threads\",pod=\"$pod\"})",
       "legendFormat": "active_threads"
      },
      {
       "expr": "group by(pod, __name__) ({__name__=\"queue_${core_queue}_scheduled_tasks\",pod=\"$pod\"})",
       "legendFormat": "scheduled_tasks"
      },
      {
       "expr": "group by(pod, __name__)({__name__=\"queue_${core_queue}_pool_size\",pod=\"$pod\"})",
       "legendFormat": "pool_size"
      }
     ]
    }
   ]
  },
  {
   "title": "Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Events",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by (name_label, pod) (rate(label_replace({__name__=~\"events_.*_total\",pod=\"$pod\"},\"name_label\",\"$1\",\"__name__\", \"(.+)\")[2m:]))",
       "legendFormat": "{{name_label}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Git",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "upload-pack phase latency [$upload_pack_operation] REVIEW: add rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "repeat": "upload_pack_operation",
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "max({__name__=~'git_upload_pack_phase_counting_${upload_pack_operation}',quantile=\"0.999\",pod=\"$pod\"}) by (__name__, pod)",
       "legendFormat": "{{pod}} - ${upload_pack_operation}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pull replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max({__name__=~'plugins_pull_replication_replication_latency_total',pod=\"$pod\",quantile=\"0.999\"}) by (__name__, pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Retries",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by (pod) (rate(plugins_pull_replication_replication_retries_total_count[1m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}