{
 "title": "Gerrit - Overview",
 "tags": [ "gerrit" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "Gerrit Instance",
    "query": {
     "query": "label_values(git_upload_pack_phase_writing_total,pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Gerrit Version",
   "type": "table-old",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max(gerrit_build_info{pod=\"$pod\"}) by (pod, version, revision, javaversion)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(rate(proc_cpu_usage{pod=\"$pod\"}[2m])/proc_cpu_num_cores{pod=\"$pod\"})*100",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Heap Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(proc_jvm_memory_heap_used{pod=\"$pod\"}/proc_jvm_memory_heap_committed{pod=\"$pod\"})*100",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Live Threads",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "proc_jvm_thread_num_daemon_live{pod=\"$pod\"}",
     "legendFormat": "current (daemon)"
    },
    {
     "expr": "proc_jvm_thread_num_live{pod=\"$pod\"}",
     "legendFormat": "current (total)"
    },
    {
     "expr": "proc_jvm_thread_num_peak_live{pod=\"$pod\"}",
     "legendFormat": "peak"
    }
   ]
  },
  {
   "title": "REST API latency (0.99 quantile)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "http_server_rest_api_server_latency_total{quantile=\"0.99\", pod=\"$pod\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "HTTP Request Error Rate (last 5 min)",
   "type": "gauge",
   "description": "Excludes 404 and 401, since these error codes are caused by client behaviour and are overrepresented in the data.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(increase(http_server_error_count_total_total{pod=\"$pod\"}[5m]) - increase(http_server_error_count_404_total{pod=\"$pod\"}[5m]) - increase(http_server_error_count_401_total{pod=\"$pod\"}[5m])) / (increase(http_server_success_count_total_total{pod=\"$pod\"}[5m]) + increase(http_server_error_count_total_total{pod=\"$pod\"}[5m]) - increase(http_server_error_count_404_total{pod=\"$pod\"}[5m]) - increase(http_server_error_count_401_total{pod=\"$pod\"}[5m]))*100",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Gerrit Availability",
   "type": "graph",
   "gridPos": { "h": 11, "w": 18, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "up{pod=\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Gerrit Availability [last 24h]",
   "type": "stat",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(up{pod=\"$pod\"}[1d])*100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Gerrit Events (last 5 min)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 18, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "Count [5 min]" }
   ],
   "targets": [
    {
     "expr": "increase(events_assignee_changed_total{pod=\"$pod\"}[5m])",
     "legendFormat": "assignee changed"
    },
    {
     "expr": "increase(events_change_abandoned_total{pod=\"$pod\"}[5m])",
     "legendFormat": "change abandoned"
    },
    {
     "expr": "increase(events_change_merged_total{pod=\"$pod\"}[5m])",
     "legendFormat": "change merged"
    },
    {
     "expr": "increase(events_comment_added_total{pod=\"$pod\"}[5m])",
     "legendFormat": "comment added"
    },
    {
     "expr": "increase(events_patchset_created_total{pod=\"$pod\"}[5m])",
     "legendFormat": "patchset created"
    },
    {
     "expr": "increase(events_change_abandoned_total{pod=\"$pod\"}[5m])",
     "legendFormat": "change abandoned"
    },
    {
     "expr": "increase(events_ref_replicated_total{pod=\"$pod\"}[5m])",
     "legendFormat": "ref replicated"
    },
    {
     "expr": "increase(events_ref_updated_total{pod=\"$pod\"}[5m])",
     "legendFormat": "ref updated"
    },
    {
     "expr": "increase(events_reviewer_added_total{pod=\"$pod\"}[5m])",
     "legendFormat": "reviewer added"
    },
    {
     "expr": "increase(events_reviewer_deleted_total{pod=\"$pod\"}[5m])",
     "legendFormat": "reviewer deleted"
    },
    {
     "expr": "increase(events_topic_changed_total{pod=\"$pod\"}[5m])",
     "legendFormat": "topic changed"
    },
    {
     "expr": "increase(events_vote_deleted_total{pod=\"$pod\"}[5m])",
     "legendFormat": "vote deleted"
    },
    {
     "expr": "increase(events_wip_state_changed_total{pod=\"$pod\"}[5m])",
     "legendFormat": "wip state changed"
    }
   ]
  },
  {
   "title": "Git Fetch/Clone upload-pack requests (last 5 min)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "Count [5 min]" }
   ],
   "targets": [
    {
     "expr": "increase(git_upload_pack_request_count_FETCH_total{pod=\"$pod\"}[5m])",
     "legendFormat": "FETCH"
    },
    {
     "expr": "increase(git_upload_pack_request_count_CLONE_total{pod=\"$pod\"}[5m])",
     "legendFormat": "CLONE"
    }
   ]
  },
  {
   "title": "HTTP response status",
   "type": "graph",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "(increase(http_server_success_count_200_total{pod=\"$pod\"}[2m]))/2",
     "legendFormat": "200"
    },
    {
     "expr": "(increase(http_server_success_count_201_total{pod=\"$pod\"}[2m]))/2",
     "legendFormat": "201"
    },
    {
     "expr": "(increase(http_server_success_count_204_total{pod=\"$pod\"}[2m]))/2",
     "legendFormat": "204"
    },
    {
     "expr": "(increase(http_server_success_count_301_total{pod=\"$pod\"}[2m]))/2",
     "legendFormat": "301"
    },
    {
     "expr": "(increase(http_server_success_count_304_total{pod=\"$pod\"}[2m]))/2",
     "legendFormat": "304"
    },
    {
     "expr": "(increase(http_server_error_count_400_total{pod=\"$pod\"}[2m]))/2",
     "legendFormat": "400"
    },
    {
     "expr": "(increase(http_server_error_count_401_total{pod=\"$pod\"}[2m]))/2",
     "legendFormat": "401"
    },
    {
     "expr": "(increase(http_server_error_count_403_total{pod=\"$pod\"}[2m]))/2",
     "legendFormat": "403"
    },
    {
     "expr": "(increase(http_server_error_count_404_total{pod=\"$pod\"}[2m]))/2",
     "legendFormat": "404"
    },
    {
     "expr": "(increase(http_server_error_count_405_total{pod=\"$pod\"}[2m]))/2",
     "legendFormat": "405"
    },
    {
     "expr": "(increase(http_server_error_count_409_total{pod=\"$pod\"}[2m]))/2",
     "legendFormat": "409"
    },
    {
     "expr": "(increase(http_server_error_count_412_total{pod=\"$pod\"}[2m]))/2",
     "legendFormat": "412"
    },
    {
     "expr": "(increase(http_server_error_count_422_total{pod=\"$pod\"}[2m]))/2",
     "legendFormat": "422"
    },
    {
     "expr": "(increase(http_server_error_count_500_total{pod=\"$pod\"}[2m]))/2",
     "legendFormat": "500"
    },
    {
     "expr": "(increase(http_server_error_count_501_total{pod=\"$pod\"}[2m]))/2",
     "legendFormat": "501"
    },
    {
     "expr": "(increase(http_server_error_count_503_total{pod=\"$pod\"}[2m]))/2",
     "legendFormat": "503"
    }
   ]
  }
 ]
}