{
 "title": "Gerrit -  Multisite",
 "description": "Metrics dashboard for Gerrit multi-site",
 "tags": [ "gerrit" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Window", "label": "Aggregation window", "query": "1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "Events broker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Publisher Successes",
   "type": "graph",
   "description": "Number of published messages to the Kafka Broker, by node",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (delta(plugins_multi_site_multi_site_broker_broker_message_publisher_counter_broker_msg_publisher_counter_total[$Window]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Publisher Successes",
   "type": "graph",
   "description": "Number of published messages to the Kafka Broker, by node",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (delta(plugins_multi_site_multi_site_broker_broker_message_publisher_counter_broker_msg_publisher_counter_total[$Window]))",
     "legendFormat": "{{pod}} "
    }
   ]
  },
  {
   "title": "Subscriber message consumer count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "#messages" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (delta(plugins_multi_site_multi_site_subscriber_subscriber_message_consumer_counter_total_total[$Window]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Live Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Split Brain Prevented",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (increase(multi_site_validation_git_update_split_brain_prevented_total_total[$Window]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pull Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Max Pull Replication Latency - ApplyObject - E2E",
   "type": "graph",
   "description": "Max Pull Replication Latency - E2E  by destination",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "max({__name__=~'plugins_pull_replication_apply_object_end_2_end_latency_total',quantile=\"0.999\"}) by (__name__, pod)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{pod}}",
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Max Pull Replication Latency - E2E",
   "type": "timeseries",
   "description": "Max Pull Replication Latency - E2E  by destination",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "max({__name__=~'plugins_pull_replication_replication_end_2_end_latency_total',quantile=\"0.999\"}) by (__name__, pod)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{pod}}",
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Replication lag",
   "type": "graph",
   "description": "Overall lag of the repositories version compared to the global ref-db version",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (avg_over_time(plugins_multi_site_multi_site_subscriber_subscriber_replication_status_sec_behind[$Window]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Replication retries",
   "type": "graph",
   "description": "Overall lag of the repositories version compared to the global ref-db version",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (delta(plugins_pull_replication_replication_retries_total_count[$Window]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Pull replication tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "In flight",
   "type": "graph",
   "description": "Number of tasks currently being executed",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (plugins_pull_replication_tasks_inflight_gerrit_1{pod=\"gerrit-0\"} + plugins_pull_replication_tasks_inflight_gerrit_2{pod=\"gerrit-0\"})",
     "legendFormat": "gerrit-0 "
    },
    {
     "expr": "sum by (pod) (plugins_pull_replication_tasks_inflight_gerrit_0{pod=\"gerrit-1\"} + plugins_pull_replication_tasks_inflight_gerrit_2{pod=\"gerrit-1\"})",
     "legendFormat": "gerrit-1"
    },
    {
     "expr": "sum by (pod) (plugins_pull_replication_tasks_inflight_gerrit_0{pod=\"gerrit-2\"} + plugins_pull_replication_tasks_inflight_gerrit_1{pod=\"gerrit-2\"})",
     "legendFormat": "gerrit-2"
    }
   ]
  },
  {
   "title": "Pending",
   "type": "graph",
   "description": "Number of tasks waiting to be executed.",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (plugins_pull_replication_tasks_pending_gerrit_1{pod=\"gerrit-0\"} + plugins_pull_replication_tasks_pending_gerrit_2{pod=\"gerrit-0\"})",
     "legendFormat": "gerrit-0 "
    },
    {
     "expr": "sum by (pod) (plugins_pull_replication_tasks_pending_gerrit_0{pod=\"gerrit-1\"} + plugins_pull_replication_tasks_pending_gerrit_2{pod=\"gerrit-1\"})",
     "legendFormat": "gerrit-1 "
    },
    {
     "expr": "sum by (pod) (plugins_pull_replication_tasks_pending_gerrit_0{pod=\"gerrit-2\"} + plugins_pull_replication_tasks_pending_gerrit_1{pod=\"gerrit-2\"})",
     "legendFormat": "gerrit-2 "
    }
   ]
  },
  {
   "title": "Retrying",
   "type": "graph",
   "description": "Number of tasks being retried for execution",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (delta(plugins_pull_replication_tasks_retrying_total[$Window]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Failed maximum retries",
   "type": "graph",
   "description": "Number of tasks that have reached their maximum retry count but never succeeded",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (delta(plugins_pull_replication_tasks_failed_max_retries_total[$Window]))",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}