{
 "title": "Gerrit - Queues",
 "tags": [ "gerrit" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "Gerrit Instance",
    "query": {
     "query": "label_values(git_upload_pack_phase_writing_total,pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "SSH threads",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Threads" }
   ],
   "targets": [
    {
     "expr": "queue_ssh_batch_worker_active_threads{pod=\"$pod\"}",
     "legendFormat": "batch threads"
    },
    {
     "expr": "queue_ssh_batch_worker_pool_size{pod=\"$pod\"}",
     "legendFormat": "batch pool size"
    },
    {
     "expr": "queue_ssh_interactive_worker_active_threads{pod=\"$pod\"}",
     "legendFormat": "interactive threads"
    },
    {
     "expr": "queue_ssh_interactive_worker_pool_size{pod=\"$pod\"}",
     "legendFormat": "interactive pool size"
    }
   ]
  },
  {
   "title": "HTTP threads",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Threads" }
   ],
   "targets": [
    {
     "expr": "http_server_jetty_threadpool_active_threads{pod=\"$pod\"}",
     "legendFormat": "active threads"
    },
    {
     "expr": "http_server_jetty_threadpool_reserved_threads{pod=\"$pod\"}",
     "legendFormat": "reserved threads"
    },
    {
     "expr": "http_server_jetty_threadpool_max_pool_size{pod=\"$pod\"}",
     "legendFormat": "max pool size"
    },
    {
     "expr": "http_server_jetty_threadpool_pool_size{pod=\"$pod\"}",
     "legendFormat": "pool size"
    }
   ]
  },
  {
   "title": "INDEX threads",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Threads" }
   ],
   "targets": [
    {
     "expr": "queue_index_batch_active_threads{pod=\"$pod\"}",
     "legendFormat": "batch threads"
    },
    {
     "expr": "queue_index_batch_pool_size{pod=\"$pod\"}",
     "legendFormat": "batch pool size"
    },
    {
     "expr": "queue_index_interactive_active_threads{pod=\"$pod\"}",
     "legendFormat": "interactive threads"
    },
    {
     "expr": "queue_index_interactive_pool_size{pod=\"$pod\"}",
     "legendFormat": "interactive pool size"
    }
   ]
  },
  {
   "title": "SSH queue",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Tasks" }
   ],
   "targets": [
    {
     "expr": "queue_ssh_batch_worker_scheduled_tasks{pod=\"$pod\"}",
     "legendFormat": "batch"
    },
    {
     "expr": "queue_ssh_interactive_worker_scheduled_tasks{pod=\"$pod\"}",
     "legendFormat": "interactive"
    }
   ]
  },
  {
   "title": "HTTP queue",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Tasks" }
   ],
   "targets": [
    {
     "expr": "http_server_jetty_threadpool_queue_size{pod=\"$pod\"}",
     "legendFormat": "http"
    }
   ]
  },
  {
   "title": "INDEX queue",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Tasks" }
   ],
   "targets": [
    {
     "expr": "queue_index_batch_scheduled_tasks{pod=\"$pod\"}",
     "legendFormat": "batch"
    },
    {
     "expr": "queue_index_interactive_scheduled_tasks{pod=\"$pod\"}",
     "legendFormat": "interactive"
    }
   ]
  },
  {
   "title": "MISC threads",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "Threads" }
   ],
   "targets": [
    {
     "expr": "queue_ssh_stream_worker_active_threads{pod=\"$pod\"}",
     "legendFormat": "stream threads"
    },
    {
     "expr": "queue_ssh_stream_worker_pool_size{pod=\"$pod\"}",
     "legendFormat": "stream pool size"
    },
    {
     "expr": "queue_send_email_active_threads{pod=\"$pod\"}",
     "legendFormat": "email threads"
    },
    {
     "expr": "queue_send_email_pool_size{pod=\"$pod\"}",
     "legendFormat": "email pool size"
    },
    {
     "expr": "queue_receive_commits_active_threads{pod=\"$pod\"}",
     "legendFormat": "receive-commit threads"
    },
    {
     "expr": "queue_receive_commits_pool_size{pod=\"$pod\"}",
     "legendFormat": "receive-commit pool size"
    }
   ]
  },
  {
   "title": "REST API request rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "reqps", "label": "Threads" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_rest_api_count_total_total{pod=\"$pod\"}[5m])",
     "legendFormat": "REST API request rate"
    }
   ]
  },
  {
   "title": "MISC queues",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short", "label": "Tasks" }
   ],
   "targets": [
    {
     "expr": "queue_ssh_stream_worker_scheduled_tasks{pod=\"$pod\"}",
     "legendFormat": "stream threads"
    },
    {
     "expr": "queue_send_email_scheduled_tasks{pod=\"$pod\"}",
     "legendFormat": "email threads"
    },
    {
     "expr": "queue_receive_commits_scheduled_tasks{pod=\"$pod\"}",
     "legendFormat": "receive-commit threads"
    }
   ]
  }
 ]
}