{
 "title": "Process",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "instance", "label": "Gerrit Instance", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Live Threads" }
   ],
   "targets": [
    {
     "expr": "proc_jvm_thread_num_live{instance=\"$instance\"}",
     "legendFormat": "Java live threads"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes", "label": "Memory Consumption" }
   ],
   "targets": [
    {
     "expr": "proc_jvm_memory_heap_committed{instance=\"$instance\"}",
     "legendFormat": "committed heap"
    },
    {
     "expr": "proc_jvm_memory_heap_used{instance=\"$instance\"}",
     "legendFormat": "used heap"
    },
    {
     "expr": "jgit_block_cache_cache_used{instance=\"$instance\"}",
     "legendFormat": "JGit block cache"
    },
    {
     "expr": "proc_jvm_memory_non_heap_used{instance=\"$instance\"}",
     "legendFormat": "used non-heap"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "CPU cores" }
   ],
   "targets": [
    {
     "expr": "rate(proc_cpu_usage{instance=\"$instance\"}[5m])",
     "legendFormat": "used CPUs"
    }
   ]
  },
  {
   "title": "Java - % of time spent in GC",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "percentunit", "label": "GC Time" }
   ],
   "targets": [
    {
     "expr": "increase(proc_jvm_gc_time_G1_Young_Generation{instance=\"$instance\"}[2m])/increase(proc_uptime{instance=\"$instance\"}[2m])",
     "legendFormat": "gc time G1 young gen"
    },
    {
     "expr": "increase(proc_jvm_gc_time_G1_Old_Generation{instance=\"$instance\"}[2m])/increase(proc_uptime{instance=\"$instance\"}[2m])",
     "legendFormat": "gc time G1 old gen"
    }
   ]
  },
  {
   "title": "JGit block cache",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percentunit", "label": "miss ratio" }
   ],
   "targets": [
    {
     "expr": "increase(jgit_block_cache_miss_count{instance=\"$instance\"}[2m])/(increase(jgit_block_cache_hit_count{instance=\"$instance\"}[2m])+increase(jgit_block_cache_miss_count{instance=\"$instance\"}[2m]))",
     "legendFormat": "miss ratio"
    },
    {
     "expr": "increase(jgit_block_cache_eviction_count{instance=\"$instance\"}[2m])/(increase(jgit_block_cache_hit_count{instance=\"$instance\"}[2m])+increase(jgit_block_cache_miss_count{instance=\"$instance\"}[2m]))",
     "legendFormat": "eviction ratio"
    }
   ]
  },
  {
   "title": "Java open file descriptors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "Open File Descriptors" }
   ],
   "targets": [
    {
     "expr": "jgit_block_cache_open_files{instance=\"$instance\"}",
     "legendFormat": "jgit block cache"
    },
    {
     "expr": "proc_num_open_fds{instance=\"$instance\"}-jgit_block_cache_open_files{instance=\"$instance\"}",
     "legendFormat": "other"
    }
   ]
  }
 ]
}