{
 "title": "Gerrit Overview",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Gerrit Instance",
    "query": "label_values(git_upload_pack_phase_writing_total, instance)"
   },
   {
    "name": "replica",
    "label": "Replica",
    "query": "label_values(git_upload_pack_phase_writing_total{instance=\"$instance\"}, replica)"
   }
  ]
 },
 "panels": [
  {
   "title": "Gerrit Version",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max(gerrit_build_info{instance=\"$instance\",replica=\"$replica\"}) by (instance, version, revision, javaversion)"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "(rate(proc_cpu_usage{instance=\"$instance\",replica=\"$replica\"}[5m])/proc_cpu_num_cores{instance=\"$instance\",replica=\"$replica\"})*100"
    }
   ]
  },
  {
   "title": "Heap Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "(proc_jvm_memory_heap_used{instance=\"$instance\",replica=\"$replica\"}/proc_jvm_memory_heap_committed{instance=\"$instance\",replica=\"$replica\"})*100"
    }
   ]
  },
  {
   "title": "Live Threads",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 5 },
   "targets": [
    {
     "expr": "proc_jvm_thread_num_daemon_live{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "current live threads (daemon)"
    },
    {
     "expr": "proc_jvm_thread_num_live{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "current live threads"
    },
    {
     "expr": "proc_jvm_thread_num_peak_live{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "peak of live threads"
    }
   ]
  },
  {
   "title": "REST API latency (0.99 quantile)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "http_server_rest_api_server_latency_total{quantile=\"0.99\", instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "quantile {{quantile}}"
    }
   ]
  },
  {
   "title": "HTTP Request Error Rate (last 5 min)",
   "type": "gauge",
   "description": "Excludes 404 and 401, since these error codes are caused by client behaviour and are overrepresented in the data.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 11 },
   "targets": [
    {
     "expr": "(increase(http_server_error_count_total_total{instance=\"$instance\",replica=\"$replica\"}[5m]) - increase(http_server_error_count_404_total{instance=\"$instance\",replica=\"$replica\"}[5m]) - increase(http_server_error_count_401_total{instance=\"$instance\",replica=\"$replica\"}[5m])) / (increase(http_server_success_count_total_total{instance=\"$instance\",replica=\"$replica\"}[5m]) + increase(http_server_error_count_total_total{instance=\"$instance\",replica=\"$replica\"}[5m]) - increase(http_server_error_count_404_total{instance=\"$instance\",replica=\"$replica\"}[5m]) - increase(http_server_error_count_401_total{instance=\"$instance\",replica=\"$replica\"}[5m]))*100"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Gerrit Availability",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Gerrit availability [last 24h]",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(up{instance=\"$instance\",replica=\"$replica\"}[1d])*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP response status",
   "type": "graph",
   "description": "This excludes response code 404, since it is caused by an issue with the Gerrit Trigger plugin.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "(increase(http_server_success_count_200_total{instance=\"$instance\",replica=\"$replica\"}[5m]))/5",
     "legendFormat": "200"
    },
    {
     "expr": "(increase(http_server_success_count_201_total{instance=\"$instance\",replica=\"$replica\"}[5m]))/5",
     "legendFormat": "201"
    },
    {
     "expr": "(increase(http_server_success_count_204_total{instance=\"$instance\",replica=\"$replica\"}[5m]))/5",
     "legendFormat": "204"
    },
    {
     "expr": "(increase(http_server_success_count_301_total{instance=\"$instance\",replica=\"$replica\"}[5m]))/5",
     "legendFormat": "301"
    },
    {
     "expr": "(increase(http_server_success_count_304_total{instance=\"$instance\",replica=\"$replica\"}[5m]))/5",
     "legendFormat": "304"
    },
    {
     "expr": "(increase(http_server_error_count_400_total{instance=\"$instance\",replica=\"$replica\"}[5m]))/5",
     "legendFormat": "400"
    },
    {
     "expr": "(increase(http_server_error_count_401_total{instance=\"$instance\",replica=\"$replica\"}[5m]))/5",
     "legendFormat": "401"
    },
    {
     "expr": "(increase(http_server_error_count_403_total{instance=\"$instance\",replica=\"$replica\"}[5m]))/5",
     "legendFormat": "403"
    },
    {
     "expr": "(increase(http_server_error_count_404_total{instance=\"$instance\",replica=\"$replica\"}[5m]))/5",
     "legendFormat": "404"
    },
    {
     "expr": "(increase(http_server_error_count_405_total{instance=\"$instance\",replica=\"$replica\"}[5m]))/5",
     "legendFormat": "405"
    },
    {
     "expr": "(increase(http_server_error_count_409_total{instance=\"$instance\",replica=\"$replica\"}[5m]))/5",
     "legendFormat": "409"
    },
    {
     "expr": "(increase(http_server_error_count_412_total{instance=\"$instance\",replica=\"$replica\"}[5m]))/5",
     "legendFormat": "412"
    },
    {
     "expr": "(increase(http_server_error_count_422_total{instance=\"$instance\",replica=\"$replica\"}[5m]))/5",
     "legendFormat": "422"
    },
    {
     "expr": "(increase(http_server_error_count_500_total{instance=\"$instance\",replica=\"$replica\"}[5m]))/5",
     "legendFormat": "500"
    },
    {
     "expr": "(increase(http_server_error_count_501_total{instance=\"$instance\",replica=\"$replica\"}[5m]))/5",
     "legendFormat": "501"
    },
    {
     "expr": "(increase(http_server_error_count_503_total{instance=\"$instance\",replica=\"$replica\"}[5m]))/5",
     "legendFormat": "503"
    }
   ]
  },
  {
   "title": "Gerrit Events (last 5 min)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short", "label": "Count [5 min]" }
   ],
   "targets": [
    {
     "expr": "increase(events_assignee_changed_total{instance=\"$instance\",replica=\"$replica\"}[5m])",
     "legendFormat": "assignee changed"
    },
    {
     "expr": "increase(events_change_abandoned_total{instance=\"$instance\",replica=\"$replica\"}[5m])",
     "legendFormat": "change abandoned"
    },
    {
     "expr": "increase(events_change_merged_total{instance=\"$instance\",replica=\"$replica\"}[5m])",
     "legendFormat": "change merged"
    },
    {
     "expr": "increase(events_comment_added_total{instance=\"$instance\",replica=\"$replica\"}[5m])",
     "legendFormat": "comment added"
    },
    {
     "expr": "increase(events_patchset_created_total{instance=\"$instance\",replica=\"$replica\"}[5m])",
     "legendFormat": "patchset created"
    },
    {
     "expr": "increase(events_ref_replicated_total{instance=\"$instance\",replica=\"$replica\"}[5m])",
     "legendFormat": "ref replicated"
    },
    {
     "expr": "increase(events_ref_updated_total{instance=\"$instance\",replica=\"$replica\"}[5m])",
     "legendFormat": "ref updated"
    },
    {
     "expr": "increase(events_reviewer_added_total{instance=\"$instance\",replica=\"$replica\"}[5m])",
     "legendFormat": "reviewer added"
    },
    {
     "expr": "increase(events_reviewer_deleted_total{instance=\"$instance\",replica=\"$replica\"}[5m])",
     "legendFormat": "reviewer deleted"
    },
    {
     "expr": "increase(events_topic_changed_total{instance=\"$instance\",replica=\"$replica\"}[5m])",
     "legendFormat": "topic changed"
    },
    {
     "expr": "increase(events_vote_deleted_total{instance=\"$instance\",replica=\"$replica\"}[5m])",
     "legendFormat": "vote deleted"
    },
    {
     "expr": "increase(events_wip_state_changed_total{instance=\"$instance\",replica=\"$replica\"}[5m])",
     "legendFormat": "wip state changed"
    }
   ]
  },
  {
   "title": "Git Fetch/Clone upload-pack requests (last 5 min)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short", "label": "Count [5 min]" }
   ],
   "targets": [
    {
     "expr": "increase(git_upload_pack_request_count_FETCH_total{instance=\"$instance\",replica=\"$replica\"}[5m])",
     "legendFormat": "Fetch"
    },
    {
     "expr": "increase(git_upload_pack_request_count_CLONE_total{instance=\"$instance\",replica=\"$replica\"}[5m])",
     "legendFormat": "Clone"
    }
   ]
  }
 ]
}