{
 "title": "Queues",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Gerrit Instance",
    "query": "label_values(git_upload_pack_phase_writing_total, instance)"
   },
   {
    "name": "replica",
    "label": "Replica",
    "query": "label_values(git_upload_pack_phase_writing_total{instance=\"$instance\"}, replica)"
   }
  ]
 },
 "panels": [
  {
   "title": "SSH threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Threads" }
   ],
   "targets": [
    {
     "expr": "queue_ssh_batch_worker_active_threads{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "batch threads"
    },
    {
     "expr": "queue_ssh_batch_worker_pool_size{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "batch pool size"
    },
    {
     "expr": "queue_ssh_interactive_worker_active_threads{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "interactive threads"
    },
    {
     "expr": "queue_ssh_interactive_worker_pool_size{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "interactive pool size"
    }
   ]
  },
  {
   "title": "HTTP threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "threads" }
   ],
   "targets": [
    {
     "expr": "http_server_jetty_threadpool_active_threads{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "active threads"
    },
    {
     "expr": "http_server_jetty_threadpool_reserved_threads{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "reserved threads"
    },
    {
     "expr": "http_server_jetty_threadpool_max_pool_size{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "max pool size"
    },
    {
     "expr": "http_server_jetty_threadpool_pool_size{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "pool size"
    }
   ]
  },
  {
   "title": "INDEX threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Threads" }
   ],
   "targets": [
    {
     "expr": "queue_index_batch_active_threads{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "batch threads"
    },
    {
     "expr": "queue_index_batch_pool_size{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "batch pool size"
    },
    {
     "expr": "queue_index_interactive_active_threads{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "interactive threads"
    },
    {
     "expr": "queue_index_interactive_pool_size{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "interactive pool size"
    }
   ]
  },
  {
   "title": "SSH queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Tasks" }
   ],
   "targets": [
    {
     "expr": "queue_ssh_batch_worker_scheduled_tasks{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "batch"
    },
    {
     "expr": "queue_ssh_interactive_worker_scheduled_tasks{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "interactive"
    }
   ]
  },
  {
   "title": "HTTP queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Tasks" }
   ],
   "targets": [
    {
     "expr": "http_server_jetty_threadpool_queue_size{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "http"
    }
   ]
  },
  {
   "title": "INDEX queued",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Tasks" }
   ],
   "targets": [
    {
     "expr": "queue_index_batch_scheduled_tasks{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "batch"
    },
    {
     "expr": "queue_index_interactive_scheduled_tasks{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "interactive"
    }
   ]
  },
  {
   "title": "misc. threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Threads" }
   ],
   "targets": [
    {
     "expr": "queue_ssh_stream_worker_active_threads{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "stream"
    },
    {
     "expr": "queue_ssh_stream_worker_pool_size{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "stream pool"
    },
    {
     "expr": "queue_send_email_active_threads{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "email"
    },
    {
     "expr": "queue_send_email_pool_size{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "email pool"
    },
    {
     "expr": "queue_receive_commits_active_threads{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "receive-commit"
    },
    {
     "expr": "queue_receive_commits_pool_size{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "receive-commit pool"
    }
   ]
  },
  {
   "title": "REST API request rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 10, "y": 16 },
   "yaxes": [
    { "format": "reqps", "label": "Requests/Second" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_rest_api_count_total_total{instance=\"$instance\",replica=\"$replica\"}[5m])",
     "legendFormat": "REST API request rate"
    }
   ]
  },
  {
   "title": "misc. queues",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Tasks" }
   ],
   "targets": [
    {
     "expr": "queue_ssh_stream_worker_scheduled_tasks{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "stream"
    },
    {
     "expr": "queue_send_email_scheduled_tasks{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "email"
    },
    {
     "expr": "queue_receive_commits_scheduled_tasks{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "receive-commit"
    }
   ]
  }
 ]
}