{
 "title": "Git fetch / clone",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "instance", "label": "Gerrit Instance", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  {
   "title": "CLONE count",
   "type": "graph",
   "description": "upload-pack requests",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "increase(git_upload_pack_request_count_CLONE_total{instance=\"$instance\"}[2m])/2",
     "legendFormat": "clone"
    }
   ]
  },
  {
   "title": "FETCH count",
   "type": "graph",
   "description": "upload-pack requests for fetches",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "increase(git_upload_pack_request_count_FETCH_total{instance=\"$instance\"}[2m])/2",
     "legendFormat": "fetch"
    }
   ]
  },
  {
   "title": "upload-pack pack bytes CLONE",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "git_upload_pack_pack_bytes_CLONE{instance=\"$instance\"}",
     "legendFormat": "quantile: {{quantile}}"
    }
   ]
  },
  {
   "title": "upload-pack pack bytes FETCH",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "git_upload_pack_pack_bytes_FETCH{instance=\"$instance\"}",
     "legendFormat": "quantile: {{quantile}}"
    }
   ]
  }
 ]
}