{
 "title": "Latency",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Gerrit Instance",
    "query": "label_values(git_upload_pack_phase_writing_total, instance)"
   },
   {
    "name": "replica",
    "label": "Replica",
    "query": "label_values(git_upload_pack_phase_writing_total{instance=\"$instance\"}, replica)"
   }
  ]
 },
 "panels": [
  {
   "title": "receive-commit latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "receivecommits_latency_total{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "quantile: {{quantile}}"
    }
   ]
  },
  {
   "title": "REST total latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_server_rest_api_server_latency_total{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "quantile: {{quantile}}"
    }
   ]
  },
  {
   "title": "query total latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "query_query_latency_total{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "quantile: {{quantile}}"
    }
   ]
  },
  {
   "title": "REST get change detail latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_server_rest_api_server_latency_restapi_change_GetDetail{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "quantile: {{quantile}}"
    }
   ]
  },
  {
   "title": "query changes latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "query_query_latency_changes{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "quantile: {{quantile}}"
    }
   ]
  },
  {
   "title": "REST get change diff latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_server_rest_api_server_latency_restapi_change_GetDiff{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "quantile: {{quantile}}"
    }
   ]
  },
  {
   "title": "REST change list comments latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_server_rest_api_server_latency_restapi_change_ListChangeComments{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "quantile: {{quantile}}"
    }
   ]
  },
  {
   "title": "REST get change latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_server_rest_api_server_latency_restapi_change_GetChange{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "quantile: {{quantile}}"
    }
   ]
  },
  {
   "title": "REST change list robot comments latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_server_rest_api_server_latency_restapi_change_ListChangeRobotComments{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "quantile: {{quantile}}"
    }
   ]
  },
  {
   "title": "REST get commit latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_server_rest_api_server_latency_restapi_change_GetCommit{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "quantile: {{quantile}}"
    }
   ]
  },
  {
   "title": "REST post change review latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_server_rest_api_server_latency_restapi_change_PostReview{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "quantile: {{quantile}}"
    }
   ]
  },
  {
   "title": "REST get change revision actions latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_server_rest_api_server_latency_restapi_change_GetRevisionActions{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "quantile: {{quantile}}"
    }
   ]
  }
 ]
}