{
 "title": "Caches",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Gerrit Instance",
    "query": "label_values(git_upload_pack_phase_writing_total, instance)"
   },
   {
    "name": "replica",
    "label": "Replica",
    "query": "label_values(git_upload_pack_phase_writing_total{instance=\"$instance\"}, replica)"
   }
  ]
 },
 "panels": [
  {
   "title": "ACCOUNT cache misses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "Cache Misses" }
   ],
   "targets": [
    {
     "expr": "100-caches_memory_hit_ratio_accounts{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "accounts"
    },
    {
     "expr": "100-caches_memory_hit_ratio_groups{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "groups"
    },
    {
     "expr": "100-caches_memory_hit_ratio_groups_byuuid{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "groups_byuuid"
    },
    {
     "expr": "100-caches_memory_hit_ratio_ldap_groups_byinclude{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "ldap_groups_byinclude"
    }
   ]
  },
  {
   "title": "CONFLICT cache misses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "Cache Misses" }
   ],
   "targets": [
    {
     "expr": "100-caches_memory_hit_ratio_conflicts{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "conflicts"
    },
    {
     "expr": "100-caches_memory_hit_ratio_mergeability{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "mergeability"
    }
   ]
  },
  {
   "title": "CHANGE cache misses",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent", "label": "Cache Misses" }
   ],
   "targets": [
    {
     "expr": "100-caches_memory_hit_ratio_change_kind{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "change_kind"
    },
    {
     "expr": "100-caches_memory_hit_ratio_change_notes{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "change_notes"
    },
    {
     "expr": "100-caches_memory_hit_ratio_changeid_project{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "changeid_project"
    }
   ]
  },
  {
   "title": "PROJECT cache misses",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percent", "label": "Cache Misses" }
   ],
   "targets": [
    {
     "expr": "100-caches_memory_hit_ratio_project_list{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "project list"
    },
    {
     "expr": "100-caches_memory_hit_ratio_projects{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "projects"
    }
   ]
  },
  {
   "title": "DIFF cache misses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent", "label": "Cache Misses" }
   ],
   "targets": [
    {
     "expr": "100-caches_memory_hit_ratio_diff{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "diff"
    },
    {
     "expr": "100-caches_memory_hit_ratio_diff_intraline{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "diff intraline"
    },
    {
     "expr": "100-caches_memory_hit_ratio_diff_summary{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "diff summary"
    }
   ]
  },
  {
   "title": "MISC cache misses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "percent", "label": "Cache Misses" }
   ],
   "targets": [
    {
     "expr": "100-caches_memory_hit_ratio_web_sessions{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "web sessions"
    },
    {
     "expr": "100-caches_memory_hit_ratio_sshkeys{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "sshkeys"
    },
    {
     "expr": "100-caches_memory_hit_ratio_git_tags{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "git tags"
    },
    {
     "expr": "100-caches_memory_hit_ratio_permission_sort{instance=\"$instance\",replica=\"$replica\"}",
     "legendFormat": "permission_sort"
    }
   ]
  }
 ]
}