#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ if not data.values.istio.enabled:
apiVersion: v1
kind: Secret
metadata:
  name:  loki-basic-auth
  namespace: #@ data.values.namespace
data:
  auth: #@ base64.encode(data.values.logging.loki.htpasswd)
type: Opaque
#@ end
