#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ if data.values.grafana.ldap.enabled and not data.values.tls.skipVerify:
apiVersion: v1
kind: Secret
metadata:
  name:  grafana-ca
  namespace: #@ data.values.namespace
data:
  server.ca.crt: #@ base64.encode(data.values.tls.caCert)
type: Opaque
#@ end
