#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("ldap.lib.txt", "format_ldap_toml")
apiVersion: v1
kind: Secret
metadata:
  name:  grafana-credentials
  namespace: #@ data.values.namespace
data:
  admin-user: #@ base64.encode(data.values.monitoring.grafana.admin.username)
  admin-password: #@ base64.encode(data.values.monitoring.grafana.admin.password)
  #@ if data.values.monitoring.grafana.ldap.enabled:
  ldap-toml: #@ base64.encode(format_ldap_toml())
  #@ end
type: Opaque
